### ISSUE TITLE
Convert a REID model to Onnx.

### ISSUE THREAD

**Issue by sradmard** [openvinotoolkit/training_extensions#499] opened 2021-03-25 06:45 UTC
Hi,
I would like to convert one of the pre-trained person-reid models for example [person-reidentification-retail-0270](https://github.com/openvinotoolkit/training_extensions/blob/develop/misc/pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0270.yaml) into .onnx format. I have downloaded a snapshot of the pre-trained weights from [here](https://github.com/openvinotoolkit/training_extensions/tree/develop/misc/pytorch_toolkit/object_reidentification/person_reidentification). I run the following command to convert the model to .onnx based on the instructions:
`python ../../../../external/deep-object-reid/tools/convert_to_onnx.py --config person-reidentification-retail-0270.yaml --output-name PersonREID_Test.onnx model.load_weights ~/Downloads/person-reidentification-retail-0270.pt`
However, I get the following error:
`raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: train.warmup_factor_base'`

I would really appreciate any help on that to be able to convert the .pt model into onnx.

**Comment by sovrasov** [comment] 2021-03-25 08:17
Hi. Looks like you're using an outdated version of this repo. This issue was resolved in #439. Configs for reid models don't contain `train.warmup_factor_base` key anymore.

**Comment by sradmard** [comment] 2021-03-25 18:03
@sovrasov thank you so much for your quick response. I was able to resolve that error following your advice. Now I am getting the following error while running the previous script to convert the person-reidentification-retail-0270 model with its pretrained .pt weights to onnx:

`  File "../../../../../external/deep-object-reid/tools/convert_to_onnx.py", line 36, in group_norm_symbolic
    channels_num = input.type().sizes()[1]
TypeError: 'NoneType' object is not subscriptable 
(Occurred when translating group_norm).`

Do I need to set up both datasets Market-1501, and MSMT17 for it? Or am I missing something else?

**Comment by sovrasov** [comment] 2021-03-26 08:52
I can't reproduce this issue. Do you work on virtualenv built using [this](https://github.com/openvinotoolkit/training_extensions/blob/develop/misc/pytorch_toolkit/object_reidentification/init_venv.sh) script? Also please check that you have the latest version of the deep-object-reid submodule.

**Closed** 2021-04-28 08:59 UTC
Labels: question
