### ISSUE TITLE
Can LRPNet read 2 rows

### ISSUE THREAD

**Issue by sparshgarg23** [openvinotoolkit/training_extensions#507] opened 2021-03-30 15:56 UTC
So I know in Issue #213 this was already covered.But @grib0ed0v commented that it is better to split the lines and then do single recognition.With regards to that I had a question
Let's say I use PixelLink text detector to detect multiple instances of text,wouldn't that be computationaly inefficient given that we now have two models running one for line splitting and one for recognition

**Comment by morkovka1337** [comment] 2021-04-12 12:25
Hi, @sparshgarg23! 

Sorry for the late answer and thank you for your interest to the OTE.

 The suggested approach (detect text and then recognize is) is commonly used and it does not necessarily should be computationally inefficient. In case of 1D feature processing (like in vanilla CTC algorithm) there is no way to process multirow text by design of the recognition model. 

Depends on what plate images you are going to recognize you can take a look at [PyTorch text-spotting model](https://github.com/openvinotoolkit/training_extensions/tree/develop/models/text_spotting). [Here](https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/text_spotting_demo/python) is an example of how to use OpenvinoIR models.

You can also try to use separate models:
[horizontal text detection](https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection/model_templates/horizontal-text-detection) for text detection and
[alphanumeric text recognition 0013 model](https://github.com/openvinotoolkit/training_extensions/tree/develop/misc/pytorch_toolkit/text_recognition) for text recognition.
You can find an example of use of these both networks [here](https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/text_detection_demo/cpp)
Here is an example of what I've tested: 
![image](https://user-images.githubusercontent.com/32310433/114393209-70898500-9ba2-11eb-878a-a975f55ef661.png)

If the result does not suit you, you can finetune models on your concrete dataset and get the better result.

Good luck!

**Comment by morkovka1337** [comment] 2021-04-28 09:53
Closing this issue. If you have other questions, feel free to reopen it. =)

**Closed by morkovka1337** 2021-04-28 09:53 UTC
Labels: question
