### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by zechendev** [openvinotoolkit/training_extensions#237] opened 2020-03-10 10:41 UTC
when using the nncf/exapmles/detection/train.py to train the compression model, there is a RuntimeError occurs, which in main.py 'out = net(images)', RuntimeError: only Tensors of floating point dtype can require gradients.
pytorch version: 1.4.0

**Comment by AlexanderDokuchaev** [comment] 2020-03-10 11:56
@AlexKoff88

**Comment by AlexKoff88** [comment] 2020-03-10 12:06
@zechendev,  can you please provide any details on how did you get this error?
- Command-line arguments 
- Other possible steps, such as setup, HW environment, etc.

In the meantime, I suggest trying a previous recommended version of PyTorch 1.3.1.

**Comment by vshampor** [comment] 2020-03-11 10:01
@zechendev, we can reproduce this problem and will fix it in the next NNCF release. Please use PyTorch 1.3.1 in the meanwhile.

**Comment by vshampor** [comment] 2020-04-29 13:16
It turns out that there is a bug in the PyTorch 1.4.0 as released that precluded using integer non-trainable parameters in PyTorch modules. It was only fixed in PyTorch 1.5.0.

**Closed** 2021-03-09 08:13 UTC
Labels: NNCF, bug
